// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// The Reporting APIs enable Enterprise Azure customers to
    /// programmatically pull consumption and billing data into preferred data
    /// analysis tools. Generate API Key on Enterprise portal and follow the
    /// tutorial under Help - Reporting APIs. The first section under this help
    /// article explains how to generate\retrieve the API key for the specified
    /// enrollment. &lt;a
    /// href="https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api"
    /// data-linktype="external"&gt;Billing Enterprise API official
    /// documentation&lt;/a&gt;
    /// </summary>
    public partial interface IEnterpriseReportingv3APIspreview : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IMarketplacesV3.
        /// </summary>
        IMarketplacesV3 MarketplacesV3 { get; }

        /// <summary>
        /// Gets the IPriceSheetsV3.
        /// </summary>
        IPriceSheetsV3 PriceSheetsV3 { get; }

        /// <summary>
        /// Gets the IReservedInstancesV3.
        /// </summary>
        IReservedInstancesV3 ReservedInstancesV3 { get; }

        /// <summary>
        /// Gets the IUsageDetailsV3.
        /// </summary>
        IUsageDetailsV3 UsageDetailsV3 { get; }

    }
}
