// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for MarketplacesV3.
    /// </summary>
    public static partial class MarketplacesV3Extensions
    {
            /// <summary>
            /// Gets the marketplace charges by custom date range.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number
            /// </param>
            /// <param name='startTime'>
            /// The start time of the date range
            /// </param>
            /// <param name='endTime'>
            /// The end time of the date range
            /// </param>
            public static IList<MarketplacePropertiesV3> GetMarketplaces(this IMarketplacesV3 operations, string enrollmentNumber, System.DateTime startTime, System.DateTime endTime)
            {
                return operations.GetMarketplacesAsync(enrollmentNumber, startTime, endTime).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the marketplace charges by custom date range.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number
            /// </param>
            /// <param name='startTime'>
            /// The start time of the date range
            /// </param>
            /// <param name='endTime'>
            /// The end time of the date range
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<MarketplacePropertiesV3>> GetMarketplacesAsync(this IMarketplacesV3 operations, string enrollmentNumber, System.DateTime startTime, System.DateTime endTime, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMarketplacesWithHttpMessagesAsync(enrollmentNumber, startTime, endTime, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets the marketplace charges for the current billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number
            /// </param>
            public static IList<MarketplacePropertiesV3> GetMarketplaces1(this IMarketplacesV3 operations, string enrollmentNumber)
            {
                return operations.GetMarketplaces1Async(enrollmentNumber).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the marketplace charges for the current billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<MarketplacePropertiesV3>> GetMarketplaces1Async(this IMarketplacesV3 operations, string enrollmentNumber, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMarketplaces1WithHttpMessagesAsync(enrollmentNumber, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets the marketplace charges for the provided billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number
            /// </param>
            /// <param name='billingPeriod'>
            /// The billing period id
            /// </param>
            public static IList<MarketplacePropertiesV3> GetMarketplaces2(this IMarketplacesV3 operations, string enrollmentNumber, string billingPeriod)
            {
                return operations.GetMarketplaces2Async(enrollmentNumber, billingPeriod).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the marketplace charges for the provided billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number
            /// </param>
            /// <param name='billingPeriod'>
            /// The billing period id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<MarketplacePropertiesV3>> GetMarketplaces2Async(this IMarketplacesV3 operations, string enrollmentNumber, string billingPeriod, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMarketplaces2WithHttpMessagesAsync(enrollmentNumber, billingPeriod, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
