// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for UsageDetailsV3.
    /// </summary>
    public static partial class UsageDetailsV3Extensions
    {
            /// <summary>
            /// Gets the usage details by custom date range
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number.
            /// </param>
            /// <param name='startTime'>
            /// The start time
            /// </param>
            /// <param name='endTime'>
            /// The end time
            /// </param>
            public static PagedJsonDataTitaniumJuly Get(this IUsageDetailsV3 operations, string enrollmentNumber, System.DateTime startTime, System.DateTime endTime)
            {
                return operations.GetAsync(enrollmentNumber, startTime, endTime).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the usage details by custom date range
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number.
            /// </param>
            /// <param name='startTime'>
            /// The start time
            /// </param>
            /// <param name='endTime'>
            /// The end time
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagedJsonDataTitaniumJuly> GetAsync(this IUsageDetailsV3 operations, string enrollmentNumber, System.DateTime startTime, System.DateTime endTime, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(enrollmentNumber, startTime, endTime, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets the usage details by current billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number.
            /// </param>
            public static PagedJsonDataTitaniumJuly GetByCurrentBillingPeriod(this IUsageDetailsV3 operations, string enrollmentNumber)
            {
                return operations.GetByCurrentBillingPeriodAsync(enrollmentNumber).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the usage details by current billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagedJsonDataTitaniumJuly> GetByCurrentBillingPeriodAsync(this IUsageDetailsV3 operations, string enrollmentNumber, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByCurrentBillingPeriodWithHttpMessagesAsync(enrollmentNumber, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets the usage details by billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number.
            /// </param>
            /// <param name='billingPeriod'>
            /// The billing period.
            /// </param>
            public static PagedJsonDataTitaniumJuly GetByBillingPeriod(this IUsageDetailsV3 operations, string enrollmentNumber, string billingPeriod)
            {
                return operations.GetByBillingPeriodAsync(enrollmentNumber, billingPeriod).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the usage details by billing period.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enrollmentNumber'>
            /// The enrollment number.
            /// </param>
            /// <param name='billingPeriod'>
            /// The billing period.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagedJsonDataTitaniumJuly> GetByBillingPeriodAsync(this IUsageDetailsV3 operations, string enrollmentNumber, string billingPeriod, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByBillingPeriodWithHttpMessagesAsync(enrollmentNumber, billingPeriod, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
