// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MarketplacePropertiesV3
    {
        /// <summary>
        /// Initializes a new instance of the MarketplacePropertiesV3 class.
        /// </summary>
        public MarketplacePropertiesV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MarketplacePropertiesV3 class.
        /// </summary>
        public MarketplacePropertiesV3(string id = default(string), string subscriptionGuid = default(string), string subscriptionName = default(string), string meterId = default(string), System.DateTime? usageStartDate = default(System.DateTime?), System.DateTime? usageEndDate = default(System.DateTime?), string offerName = default(string), string resourceGroup = default(string), string instanceId = default(string), string additionalInfo = default(string), string tags = default(string), string orderNumber = default(string), string unitOfMeasure = default(string), string costCenter = default(string), int? accountId = default(int?), string accountName = default(string), string accountOwnerId = default(string), int? departmentId = default(int?), string departmentName = default(string), string publisherName = default(string), string planName = default(string), double? consumedQuantity = default(double?), double? resourceRate = default(double?), double? extendedCost = default(double?), bool? isRecurringCharge = default(bool?))
        {
            Id = id;
            SubscriptionGuid = subscriptionGuid;
            SubscriptionName = subscriptionName;
            MeterId = meterId;
            UsageStartDate = usageStartDate;
            UsageEndDate = usageEndDate;
            OfferName = offerName;
            ResourceGroup = resourceGroup;
            InstanceId = instanceId;
            AdditionalInfo = additionalInfo;
            Tags = tags;
            OrderNumber = orderNumber;
            UnitOfMeasure = unitOfMeasure;
            CostCenter = costCenter;
            AccountId = accountId;
            AccountName = accountName;
            AccountOwnerId = accountOwnerId;
            DepartmentId = departmentId;
            DepartmentName = departmentName;
            PublisherName = publisherName;
            PlanName = planName;
            ConsumedQuantity = consumedQuantity;
            ResourceRate = resourceRate;
            ExtendedCost = extendedCost;
            IsRecurringCharge = isRecurringCharge;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionGuid")]
        public string SubscriptionGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionName")]
        public string SubscriptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meterId")]
        public string MeterId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usageStartDate")]
        public System.DateTime? UsageStartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usageEndDate")]
        public System.DateTime? UsageEndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offerName")]
        public string OfferName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceGroup")]
        public string ResourceGroup { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instanceId")]
        public string InstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "additionalInfo")]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public string Tags { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitOfMeasure")]
        public string UnitOfMeasure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "costCenter")]
        public string CostCenter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public int? AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountOwnerId")]
        public string AccountOwnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "departmentId")]
        public int? DepartmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "departmentName")]
        public string DepartmentName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publisherName")]
        public string PublisherName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "planName")]
        public string PlanName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consumedQuantity")]
        public double? ConsumedQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceRate")]
        public double? ResourceRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extendedCost")]
        public double? ExtendedCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isRecurringCharge")]
        public bool? IsRecurringCharge { get; set; }

    }
}
