// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PagedJsonDataTitaniumJuly
    {
        /// <summary>
        /// Initializes a new instance of the PagedJsonDataTitaniumJuly class.
        /// </summary>
        public PagedJsonDataTitaniumJuly()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PagedJsonDataTitaniumJuly class.
        /// </summary>
        public PagedJsonDataTitaniumJuly(string id = default(string), IList<UsageDetailsDeNormalizedTitaniumJuly> data = default(IList<UsageDetailsDeNormalizedTitaniumJuly>), string nextLink = default(string))
        {
            Id = id;
            Data = data;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<UsageDetailsDeNormalizedTitaniumJuly> Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
