// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PriceSheetV3
    {
        /// <summary>
        /// Initializes a new instance of the PriceSheetV3 class.
        /// </summary>
        public PriceSheetV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PriceSheetV3 class.
        /// </summary>
        public PriceSheetV3(string offerId = default(string), string id = default(string), string billingPeriodId = default(string), string meterId = default(string), string meterName = default(string), string unitOfMeasure = default(string), double? includedQuantity = default(double?), string partNumber = default(string), double? unitPrice = default(double?), string currencyCode = default(string))
        {
            OfferId = offerId;
            Id = id;
            BillingPeriodId = billingPeriodId;
            MeterId = meterId;
            MeterName = meterName;
            UnitOfMeasure = unitOfMeasure;
            IncludedQuantity = includedQuantity;
            PartNumber = partNumber;
            UnitPrice = unitPrice;
            CurrencyCode = currencyCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offerId")]
        public string OfferId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billingPeriodId")]
        public string BillingPeriodId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meterId")]
        public string MeterId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meterName")]
        public string MeterName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitOfMeasure")]
        public string UnitOfMeasure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includedQuantity")]
        public double? IncludedQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "partNumber")]
        public string PartNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitPrice")]
        public double? UnitPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currencyCode")]
        public string CurrencyCode { get; set; }

    }
}
