// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BillingAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RIPurchaseHistoryV3Properties
    {
        /// <summary>
        /// Initializes a new instance of the RIPurchaseHistoryV3Properties
        /// class.
        /// </summary>
        public RIPurchaseHistoryV3Properties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RIPurchaseHistoryV3Properties
        /// class.
        /// </summary>
        public RIPurchaseHistoryV3Properties(string purchasingEnrollment = default(string), string armSkuName = default(string), string term = default(string), string region = default(string), string purchasingSubscriptionGuid = default(string), string purchasingSubscriptionName = default(string), string accountName = default(string), string accountOwnerEmail = default(string), string departmentName = default(string), string costCenter = default(string), string currentEnrollment = default(string), System.DateTime? eventDate = default(System.DateTime?), string reservationOrderId = default(string), string description = default(string), string eventType = default(string), double? quantity = default(double?), double? amount = default(double?), string currency = default(string), string reservationOrderName = default(string))
        {
            PurchasingEnrollment = purchasingEnrollment;
            ArmSkuName = armSkuName;
            Term = term;
            Region = region;
            PurchasingSubscriptionGuid = purchasingSubscriptionGuid;
            PurchasingSubscriptionName = purchasingSubscriptionName;
            AccountName = accountName;
            AccountOwnerEmail = accountOwnerEmail;
            DepartmentName = departmentName;
            CostCenter = costCenter;
            CurrentEnrollment = currentEnrollment;
            EventDate = eventDate;
            ReservationOrderId = reservationOrderId;
            Description = description;
            EventType = eventType;
            Quantity = quantity;
            Amount = amount;
            Currency = currency;
            ReservationOrderName = reservationOrderName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "purchasingEnrollment")]
        public string PurchasingEnrollment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "armSkuName")]
        public string ArmSkuName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "region")]
        public string Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "purchasingSubscriptionGuid")]
        public string PurchasingSubscriptionGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "purchasingSubscriptionName")]
        public string PurchasingSubscriptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountOwnerEmail")]
        public string AccountOwnerEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "departmentName")]
        public string DepartmentName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "costCenter")]
        public string CostCenter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currentEnrollment")]
        public string CurrentEnrollment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventDate")]
        public System.DateTime? EventDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reservationOrderId")]
        public string ReservationOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eventType")]
        public string EventType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public double? Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reservationOrderName")]
        public string ReservationOrderName { get; set; }

    }
}
